version: '3'
services:
  pgsqldb:
    image: postgres
    ports:
    - 5432:5432
    env_file:
    - .env
    volumes:
      - pgsql:/var/lib/pgsql
      - pgsql_config:/etc/pgsql
    networks:
      - pg_py_network
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - pgsqldb
    env_file:
      - .env
    ports:
      - "5050:80"
    networks:
      - pg_py_network
  ingestion:
    build:
      context: .
    ports:
      - 8000:5000
    depends_on:
      - pgsqldb
    volumes:
      - ./csv_data:/ingestion_script/csv_data
    networks:
      - pg_py_network
volumes:
  pgsql:
  pgsql_config:

networks:
  pg_py_network:
    driver: bridge
